/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/homePage/AddButton.vue')['default']
    CategoryTabs: typeof import('./src/components/homePage/CategoryTabs.vue')['default']
    FolderPicker: typeof import('./src/components/homePage/FolderPicker.vue')['default']
    HomeHeader: typeof import('./src/components/homePage/HomeHeader.vue')['default']
    MilkdownEditor: typeof import('./src/components/editorPage/MilkdownEditor.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NoteCard: typeof import('./src/components/homePage/NoteCard.vue')['default']
    NoteHeader: typeof import('./src/components/editorPage/NoteHeader.vue')['default']
    NoteList: typeof import('./src/components/homePage/NoteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/homePage/SearchBar.vue')['default']
    TitleBar: typeof import('./src/components/editorPage/TitleBar.vue')['default']
  }
}
